from __future__ import annotations

from .commands.common import (
    _json,
    _load_json_object,
    _root,
    _signing_key_from_env,
)
from .commands.deployment import (
    _deployment_state_path,
    cmd_deployment_create,
    cmd_deployment_guardrails,
    cmd_deployment_metrics,
    cmd_deployment_promote,
    cmd_deployment_rollback,
    cmd_deployment_status,
    cmd_deployment_verify_incident,
)
from .commands.evaluation import (
    cmd_benchmark,
    cmd_benchmark_ablate,
    cmd_benchmark_algorithms,
    cmd_benchmark_calibrate,
    cmd_benchmark_corpus_snapshot,
    cmd_benchmark_corpus_validate,
    cmd_benchmark_intervene,
    cmd_benchmark_policy_advisor,
    cmd_benchmark_statistics,
)
from .commands.learning import (
    cmd_learning_contextual_policy,
    cmd_learning_evaluate,
    cmd_learning_manifest,
    cmd_learning_record_outcome,
    cmd_learning_shadow_evaluate,
    cmd_learning_status,
    cmd_learning_verify_manifest,
)
from .commands.memory import (
    cmd_memory_add,
    cmd_memory_export,
    cmd_memory_list,
    cmd_memory_prune,
    cmd_memory_search,
)
from .commands.parser import build_parser
from .commands.production import (
    cmd_production_reconcile,
    cmd_production_status,
    cmd_production_sync,
)
from .commands.workspace import (
    _cmd_repos_set,
    _decision,
    _format_brief,
    _resolve_changed,
    cmd_bootstrap,
    cmd_brief,
    cmd_compress,
    cmd_context,
    cmd_doctor,
    cmd_handoff,
    cmd_index,
    cmd_init,
    cmd_repos_exclude,
    cmd_repos_include,
    cmd_repos_list,
    cmd_repos_refresh,
    cmd_route,
    cmd_setup,
    cmd_stats,
    cmd_verify,
)


__all__ = [
    "_cmd_repos_set",
    "_decision",
    "_deployment_state_path",
    "_format_brief",
    "_json",
    "_load_json_object",
    "_resolve_changed",
    "_root",
    "_signing_key_from_env",
    "build_parser",
    "cmd_benchmark",
    "cmd_benchmark_ablate",
    "cmd_benchmark_algorithms",
    "cmd_benchmark_calibrate",
    "cmd_benchmark_corpus_snapshot",
    "cmd_benchmark_corpus_validate",
    "cmd_benchmark_intervene",
    "cmd_benchmark_policy_advisor",
    "cmd_benchmark_statistics",
    "cmd_bootstrap",
    "cmd_brief",
    "cmd_compress",
    "cmd_context",
    "cmd_deployment_create",
    "cmd_deployment_guardrails",
    "cmd_deployment_metrics",
    "cmd_deployment_promote",
    "cmd_deployment_rollback",
    "cmd_deployment_status",
    "cmd_deployment_verify_incident",
    "cmd_doctor",
    "cmd_handoff",
    "cmd_index",
    "cmd_init",
    "cmd_learning_contextual_policy",
    "cmd_learning_evaluate",
    "cmd_learning_manifest",
    "cmd_learning_record_outcome",
    "cmd_learning_shadow_evaluate",
    "cmd_learning_status",
    "cmd_learning_verify_manifest",
    "cmd_memory_add",
    "cmd_memory_export",
    "cmd_memory_list",
    "cmd_memory_prune",
    "cmd_memory_search",
    "cmd_production_reconcile",
    "cmd_production_status",
    "cmd_production_sync",
    "cmd_repos_exclude",
    "cmd_repos_include",
    "cmd_repos_list",
    "cmd_repos_refresh",
    "cmd_route",
    "cmd_setup",
    "cmd_stats",
    "cmd_verify",
    "main",
]


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)
